---
    - name: My fist playbook
      hosts: localhost
      become: true
      become_method: sudo
      tasks:
        - name: install package
          package: 
            name: httpd
            statecd ..: installed
