---
    - name: Update Kernel
      hosts: all
      become: true
      become_method: sudo
      user: centos
      tasks:
        - name: Install package on all
          package:
            name: kernel
            state: latest

        # - name: reboot
        #   shell: reboot
        #   ignore_errors: true

        # - name: update Kernel
        #   when: when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")
        #   dnf:
        #     name: kernel
        #     state: latest

        # - name: update Kernel
        #   when: when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")
        #   dnf:
        #     name: kernel
        #     state: latest

        # - name: update Kernel
        #   when: when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")
        #   dnf:
        #     name: kernel
        #     state: latest     
